name: MVA Generator

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  mva-generator:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          npm install airac-cc

      - name: Get AIRAC info using JS
        id: airac
        run: |
          node .github/workflows/get-airac.js > airac.env
          cat airac.env | grep START | sed 's/^/NEXT_/' >> $GITHUB_ENV
          cat airac.env | grep END | sed 's/^/NEXT_/' >> $GITHUB_ENV
          cat airac.env | grep IDENTIFIER >> $GITHUB_ENV

      - name: Check if it's 2 days before AIRAC
        id: check-date
        run: |
          TARGET=$(date -d "$NEXT_START -2 days" +%F)
          TODAY=$(date -u +%F)
          echo "AIRAC Identifier: $IDENTIFIER"
          echo "AIRAC Start: $NEXT_START"
          echo "Today: $TODAY"
          echo "Target Run Day: $TARGET"
          if [ "$TODAY" = "$TARGET" ]; then
            echo "run_next=true" >> $GITHUB_OUTPUT
          else
            echo "run_next=false" >> $GITHUB_OUTPUT
          fi

      - name: Download DFS CSV
        if: steps.check-date.outputs.run_next == 'true'
        run: |
          FILE_URL="https://aip.dfs.de/datasets/scripts/getItem.php?amdt=1&content=ED_MVA_${NEXT_START}_${NEXT_END}_revision.csv"
          echo "Downloading: $FILE_URL"
          curl -fSL "$FILE_URL" -o data.csv

      - name: Run Python script
        if: steps.check-date.outputs.run_next == 'true'
        run: |
          python mva_parser.py data.csv output.txt

      - name: Upload output as artifact
        if: steps.check-date.outputs.run_next == 'true'
        uses: actions/upload-artifact@v4
        with:
          name: airac-output-${{ env.IDENTIFIER }}
          path: output.txt
